# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@70a101a14bbdeed13e7a42a9ed06b35c9e9e826e
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
